### ISSUE TITLE
DEMO!!

### ISSUE THREAD

**Issue by ghost** [EatBytes/Fuzzer#6]
first thanks for this job but can you put a quick demo please

**Comment by raskyer** [comment]
Thanks !
Of course of course. It's coming. I can't tell you it'll be available today but maybe tomorow :)

**Comment by ghost** [comment]
ah ok thanks man

**Comment by raskyer** [comment]
Now you should have all the information to run this perfectly ! (New version 1.5 available)
Let me know if you encounter problem :)

**Comment by ghost** [comment]
awsome man i will see your Demo...thanks a lot
